name: student_management_provider
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  anim_search_bar: ^2.0.3
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  hero_animation: ^1.1.4
  image_picker: ^1.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
